name: test_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add this section for your images
  assets:
    - assets/images/brightbitelogo.png
    - assets/images/toothbrush_toothpaste_icon.png
    - assets/images/brushing_teeth.png
    - assets/images/adult_people.png
    - assets/images/back_arrow.png
    - assets/images/child.png
    - assets/images/crown.png
    - assets/images/dental_chair.png
    - assets/images/dental_picks.png
    - assets/images/drill_tooth.png
    - assets/images/elderly_people.png
    - assets/images/electric_toothbrush.png
    - assets/images/examine_tooth.png
    - assets/images/extract_tooth.png
    - assets/images/floss_teeth.png
    - assets/images/life_stages.png
    - assets/images/manual_toothbrush.png
    - assets/images/Mouth.png
    - assets/images/mouthrinse.png
    - assets/images/other_treatment.png
    - assets/images/preventive.png
    - assets/images/string_floss.png
    - assets/images/teen_braces.png
    - assets/images/tongue_cleaner.png
    - assets/images/tooth_bacteria.png
    - assets/images/tooth_floss.png
    - assets/images/tooth_magnify.png
    - assets/images/tooth_toothbrush.png
    - assets/images/toothbrush.png

  fonts:
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/PTSerif-Italic.ttf
          style: italic
        - asset: assets/fonts/PTSerif-BoldItalic.ttf
          weight: 700
          style: italic