name: test_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0  # or the version you're using
  path_provider: ^2.0.11
  json_serializable: ^6.7.1 # Ensure this is added
  webview_flutter: ^4.10.0
  url_launcher: ^6.1.11 # or whatever the latest version is
  photo_view: ^0.14.0  # Added from main branch
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  adaptive_icon: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  # This section for images
  assets:
    - assets/images/brightbitelogo.png
    - assets/images/toothbrush_toothpaste_icon.png


    - assets/images/tooth_toothbrush.png
    - assets/images/manual_toothbrush.png


    # - assets/images/brushing_teeth.png

    - assets/images/adult_people.png
    - assets/images/baby.png 
    - assets/images/back_arrow.png
    - assets/images/child.png
    - assets/images/colgate_360_toothbrush.png
    - assets/images/colgate_slim_soft_toothbrush.png
    - assets/images/crown.png
    - assets/images/dental_chair.png
    - assets/images/dental_picks.png
    - assets/images/drill_tooth.png
    - assets/images/elderly_people.png
    - assets/images/electric_toothbrush.png
    - assets/images/examine_tooth.png
    - assets/images/extract_tooth.png
    - assets/images/floss_teeth.png
    - assets/images/GREENZLA_bamboo_toothbrush.png
    - assets/images/life_stages.png
    - assets/images/manual_toothbrush.png
    - assets/images/Mouth.png
    - assets/images/mouthrinse.png
    - assets/images/oral-b_gum_care_toothbrush.png
    - assets/images/other_treatment.png
    - assets/images/preventive.png
    - assets/images/preserve_eco_friendly_toothbrush.png
    - assets/images/sensitive.png
    - assets/images/string_floss.png
    - assets/images/teen_braces.png
    - assets/images/tongue_cleaner.png
    - assets/images/tooth_bacteria.png
    - assets/images/tooth_floss.png
    - assets/images/tooth_magnify.png
    - assets/images/tooth_toothbrush.png
    - assets/images/toothbrush.png
    - assets/images/water_flosser.png 

  fonts:
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/PTSerif-Italic.ttf
          style: italic
        - asset: assets/fonts/PTSerif-BoldItalic.ttf
          weight: 700
          style: italic