name: test_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0  # or the version you're using
  path_provider: ^2.0.11
  json_serializable: ^6.7.1 # Ensure this is added
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  adaptive_icon: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  # Add this section for your images
  assets:
    - assets/images/brightbitelogo.png
    - assets/images/toothbrush_toothpaste_icon.png

  fonts:
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/PTSerif-Italic.ttf
          style: italic
        - asset: assets/fonts/PTSerif-BoldItalic.ttf
          weight: 700
          style: italic